name: aura
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  responsive_sizer: ^3.2.0
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  riverpod: ^2.4.9
  amplify_core: ^1.6.2
  amplify_auth_cognito: ^1.6.1
  amplify_flutter: ^1.6.1
  amplify_authenticator: ^1.5.2
  animated_text_kit: ^4.2.2
  email_validator: ^2.1.17
  amplify_storage_s3: ^1.0.0
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter_reaction_button: ^3.0.0+3
  aws_common: ^0.6.3
  native_image_cropper: ^0.4.0
  flutter_bounceable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: Roboto
      fonts: 
       - asset: assets/fonts/Rajdhani-Regular-Intro-Text.ttf
       - asset: assets/fonts/RobotoFlex-Regular-Site-Text.ttf
       